### ISSUE TITLE
List of URLs graph showing only 3 urls

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#10]
Please refer to attached screen shot.
- List of teams shows all the urls tested
- But Lost of URLs and PLT is only showing first 3 urls tested.

I tried checking the setting for this graph and didn't find 3 being selected. Is this value hard coded somewhere else ?

Please clarify

![list_of_url](https://user-images.githubusercontent.com/308490/32560602-57d98712-c4aa-11e7-8a1f-b15516619845.png)

**Comment by Verkurkie** [comment]
Yea-something seems out of order here ... the URLs column in the left table should not have 0-values because every result should always have a URL. You could have a look at the 'Discover' tab and inspect the individual records and look for `dl` field. If you want to get adventurous, you can go to the 'Dev Tools' tab and run this query:
```
GET cicd-perf/_search
{
  "aggs": {
    "URLs": {
      "terms": {
        "field": "dl",
        "size": 25
      }
    }
  },
  "size": 0
}
```
The response should look like this (list of unique URLs are inside the `aggregations.URLs.buckets` array):
```
{
  "took": 2405,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 11444159,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "URLs": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 6310630,
      "buckets": [
        {
          "key": "www.example.com/url1",
          "doc_count": 707605
        },
        {
          "key": "www.example.com/url2",
          "doc_count": 668948
        },
        {
          "key": "www.example.com/url3",
          "doc_count": 454470
        },
        {
          "key": "www.example.com/url4",
          "doc_count": 421178
        },
        ... and so on
    }
} 
```
Let me know what you find!

**Comment by vikramvi** [comment]
![discover](https://user-images.githubusercontent.com/308490/32735519-3909d082-c895-11e7-8994-791d420a7e2b.png)
![uniqueurlvaluezero](https://user-images.githubusercontent.com/308490/32735520-392ece00-c895-11e7-89ce-7891452e03c2.png)

Please refer to above screen shots, under Discover there is not `dl` field getting capture.
Also still the value for `unique URLs is 0`

**Comment by vikramvi** [comment]
One more observation
After changing web url from 
`https://www.smava.de/landing/kfzrechner?embed&placementId=1847502766&ref=9875f8f0&amount=52490&category=1&channel=desktop&data1=4&duration=84&initialPayment=0&subaffiliateid=4&vehicleBrand=Audi&vehicleKm=9625&vehicleModel=A4&vehiclePowerKw=200&vehiclePrice=52490&vehicleRegistrationYear=2016`
TO
`https://www.smava.de/landing/kfzrechner`

I could see the results as per screen shots
![short_url_1](https://user-images.githubusercontent.com/308490/32735907-5fd44034-c896-11e7-9b7f-acf7761be24c.png)
![short_url_2](https://user-images.githubusercontent.com/308490/32735908-5ff04716-c896-11e7-9fd9-b39b593bc915.png)

- On Discover page, I choose `dl` field and could see the results per screen shot

**Comment by Verkurkie** [comment]
OK - I have been able to reproduce this issue. It seems as though elasticsearch & Kibana have issues with those long URLs. I will investigate this further with some ELK experts! Hope to have a solution soon ...

**Comment by vikramvi** [comment]
Thanks for looking into this

**Comment by Verkurkie** [comment]
OK - so the root cause of this is that the elasticsearch **template** for the `cicd-perf` index was set to ignore strings > 256 characters. Long strings will be stored but they are ignored in aggregations. You can do one of two things:

### Start completely from scratch
  - stop the containers
  - delete the contents of your elasticsearch data directory
  - update `timings-docker` (git pull)
  - start the containers again
  - run the kibana import again (NOTE: arguments have changed! Check the [README](https://github.com/Verkurkie/timings-docker/blob/master/README.md#the-import-script))

### Keep your data
Follow below steps. Make sure you replace `{es_host}` with the hostname of your elasticsearch server!!

#### Overwrite template

Run the following `curl` command:
```
curl -XPUT 'https://{es_host}:9200/_template/cicd-perf' -H "Content-Type: application/json" -d'
{
  "order": 0,
  "template": "cicd-perf*",
  "settings": {
      "number_of_shards": 1
  },
  "mappings": {
      "_default_": {
          "dynamic_templates": [{
                  "string_fields": {
                      "mapping": {
                          "index": "not_analyzed",
                          "omit_norms": true,
                          "type": "string",
                          "doc_values": true
                      },
                      "match_mapping_type": "string",
                      "match": "*"
                  }
              },
              {
                  "timing_fields": {
                      "mapping": {
                          "type": "long"
                      },
                      "match_mapping_type": "*",
                      "match": "*Time"
                  }
              }
          ],
          "_all": {
              "enabled": false
          }
      }
  },
  "aliases": {

  }
}
'
```

#### Copy the existing `cicd-perf` index to a temp index

Run the following `curl` command:
```
curl -XPOST 'https://{es_host}:9200/_reindex?pretty' -H "Content-Type: application/json" -d'
{
  "source": {
    "index": "cicd-perf"
  },
  "dest": {
    "index": "cicd-perf-tmp"
  }
}
'
```

#### Delete the original index

Run the following `curl` command:
```
curl -XDELETE 'https://{es_host}:9200/cicd-perf' -H "Content-Type: application/json"
```

#### Copy the temp index back to the original index

Run the following `curl` command:
```
curl -XPOST 'https://{es_host}:9200/_reindex?pretty' -H "Content-Type: application/json" -d'
{
  "source": {
    "index": "cicd-perf-tmp"
  },
  "dest": {
    "index": "cicd-perf"
  }
}
'
```

#### Delete the temp index

Run the following `curl` command:
```
curl -XDELETE 'https://{es_host}:9200/cicd-perf-tmp' -H "Content-Type: application/json"
```

Now check your Kibana dashboard - the full URLs should show up ... lmk how that worked!

**Comment by vikramvi** [comment]
Thanks for quick fix.

After running first curl command, getting below error

`curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.`

I've tried with both values `localhost` and later `actual ip address` for `es_host`

**Comment by Verkurkie** [comment]
Are you running the `curl` command with `https://`? If so, try `http://` ... I edited the comment above to `http://` ... sorry about that! Our elasticsearch cluster is SSL and i copied the examples from my own testing ;-)

**Comment by vikramvi** [comment]
Thanks a ton for quick info :)

But after running all the curl commands, I don't see the old data it's completely empty.

**Comment by vikramvi** [comment]
Thanks a ton for detailed support @Verkurkie 

Note for anyone who lands here, after getting new code, as per above comment delete old container and pull new container.

Closing this issue as verified fixed.
