### ISSUE TITLE
docker-compose up --build downloads 2 timings images is it correct ?

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#19]
- Deleted existing 2 timings related images namely  `timingsdocker_timings`  and `mverkerk/timings `
- Later ran command `docker-compose up --build `
- After this command has successfully ran, checked the downloaded images

```
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
timingsdocker_timings                           latest              a30fab9d0bad        31 seconds ago      687MB
mverkerk/timings                                latest              684b15f69160        16 hours ago        687MB
```
-  Please clarify why is it downloading 2 images related to timings ?

**Comment by Verkurkie** [comment]
The reason was the `build: timings/` line in the `docker-compose.yml` file (in the root of this repo). The `build` instruction will cause docker-compose to use the **Dockerfile** file in the `timings/` folder and in that file, you will see `FROM mverkerk/timings:latest` ... basically, docker-compose will first pull that image (that is the second entry in your example above) and then build a new image based on any additional lines in **Dockerfile** (that results in the first entry in your example above). I realized that this is redundant so I changed `build: timings/` to `image: mverkerk/timings:latest` ... this should result in just one image.

Having said that, I may change the `:latest` tag to a version number - to avoid further conflicts. I'm not fully convinced yet that docker-compose always grabs the most recent image from hub.docker.com if there already is a local copy of "latest" ... doing so would result in multiple images that you would have to clean up over time ... if anybody know - please comment
