### ISSUE TITLE
waterfall link points to localhost even when I've set ip address for KB_HOST

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#23]
I've set kibana ip address as below

1.  ./timings/config/.config_sample.js > 
"KB_HOST": "http://10.10.100.100"
"ES_HOST": "http://10.10.100.100",

2. Also in the docker-compose.yml >
 KB_HOST: "http://10.10.100.100"

Still waterfall link takes to localhost instead of particular ip address.
This is needed so that everyone within company network should be able to access kibana dashboard

**Comment by Verkurkie** [comment]
Looks like something went wrong with the elasticsearch import/update because that is what sets the waterfall link. You can correct this yourself in **Kibana**:

- In Kibana, go to "Management"
- Click on "Index Patterns"
- Select the "**cicd-perf***" index pattern
- In the list of fields, find the `**@_uuid**` field (your can search for it using the "filter" field)
- Click on the "edit" button (all the way on the right)
- Change the hostname in the "**Url Template**" field (this should be the fully qualified hostname of the API server)
- Click on "Update Field"

Sorry about the trouble but that should do it ...

**Comment by vikramvi** [comment]
Thanks again for quick fix, it worked perfectly.  I've added this to FAQ page
