### ISSUE TITLE
Kibana visualization, dashboards, etc..

### ISSUE THREAD

**Issue by xAaeEx** [Verkurkie/timings-docker#25]
### Hello Marcel,
I’m having some trouble with kibana. I noticed that kibana doesn’t have any “Visualizations” or “Saved Objects”. So I found out that with the commit (ae7f9f3) you removed the import python script which did import those things. You stated that the script is no longer needed, but unfortunately, you didn’t specify which component would. So now, I’m kinda confused where the “magic” happens. 

_(Btw. You should also update the FAQ section Q11 that still references the import.py script)._

**Comment by Verkurkie** [comment]
Just a quick update: i have an outstanding pull request (https://github.com/godaddy/timings/pull/25) that's currently being reviewed - this update will improve the import of kibana items. I hope to publish v1.1.7 of the API in the next few days! I will update the FAQ accordingly.

**Comment by Verkurkie** [comment]
Hi Diogo! Hopefully some good news finally! I just updated the repo as well as the API (github.com/godaddy/timings). The import should now work well because the API will wait patiently for elasticsearch to be in a healthy state before it attempts the import of Kibana items. Hope this works. Please update, reference the readme.md and give it a go! lmk how it works

**Comment by Verkurkie** [comment]
Hey @xAaeEx - i will close this issue assuming things have been resolved. Feel free to open a new one if you are still having issues.
